steps:
  # Download and install Terragrunt
  - name: "gcr.io/cloud-builders/wget"
    args:
      - -O
      - /workspace/terragrunt
      - "https://github.com/gruntwork-io/terragrunt/releases/download/v0.69.13/terragrunt_linux_amd64"
    id: "download-terragrunt"

  # Make Terragrunt executable
  - name: "ubuntu"
    args: ["chmod", "+x", "/workspace/terragrunt"]
    id: "prepare-terragrunt"

  # Run Terragrunt apply-all
  - name: "hashicorp/terraform:1.6"
    entrypoint: "sh"
    secretEnv: ["GITHUB_TOKEN"]
    args:
      - "-c"
      - |
        apk add --no-cache \
          curl \
          git \
          bash \
          jq \
          wget \
          tar \
          gzip \
          python3 \
          py3-pip \
          py3-crcmod

        # Install Google Cloud SDK
        wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
        tar zxf google-cloud-sdk.tar.gz

        # Install without user input and update PATH
        ./google-cloud-sdk/install.sh --quiet --install-dir=/usr/local
        export PATH="/usr/local/google-cloud-sdk/bin:$${PATH}"

        # Verify gsutil is available
        which gsutil || echo "gsutil not found in PATH: $${PATH}"

        # Initialize gcloud (no user input required)
        gcloud config set disable_usage_reporting true
        gcloud config set project $${PROJECT_ID}

        # Configure Git to use GITHUB_TOKEN
        git config --global url."https://oauth2:$${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

        # Export the token so terragrunt can access it
        export GITHUB_TOKEN="$${GITHUB_TOKEN}"

        cd environments/stable
        /workspace/terragrunt run-all apply --terragrunt-non-interactive
    id: "terragrunt-apply"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s" # 20 minute timeout

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
