steps:
  # Get latest version
  - name: "us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder"
    args: ["get-version", "${_REPO_OWNER}", "${_REPO}"]
    secretEnv: ["GITHUB_TOKEN"]
    id: "get-version"

  # Process PR info and bump version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "bump-version"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--current-version"
      - "$$(cat current_version.txt)"
      - "--version-type"
      - "${_PR_TYPE}"
      - "--is-merge"
      - "${_IS_MERGE}"
      - "--pr-number"
      - "${_PR_NUMBER}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "bump-version"
    waitFor: ["get-version"]

  # Publish to PyPI if this is a merge to main
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder:terraform"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apk add --no-cache jq
        git config --global url."https://oauth2:$${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
        make deploy
    id: "publish"
    secretEnv: ["GITHUB_TOKEN"]
    waitFor: ["bump-version"]

  # Create GitHub release
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "create-release"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-prod"
      - "${_IS_MERGE}"
      - "--skip-asset"
    secretEnv: ["GITHUB_TOKEN"]
    id: "create-release"
    waitFor: ["publish"]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s" # 20 minute timeout

substitutions:
  _PR_TYPE: "timestamp"
  _REPO: "portfolio"
  _REPO_OWNER: ""
  _IS_MERGE: "false"
  _PR_NUMBER: ""

serviceAccount: "projects/$PROJECT_ID/serviceAccounts/cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
