steps:
  # Download and install Terragrunt
  - name: "gcr.io/cloud-builders/wget"
    args:
      - -O
      - /workspace/terragrunt
      - "https://github.com/gruntwork-io/terragrunt/releases/download/v0.69.13/terragrunt_linux_amd64"
    id: "download-terragrunt"

  # Make Terragrunt executable
  - name: "ubuntu"
    args: ["chmod", "+x", "/workspace/terragrunt"]
    id: "prepare-terragrunt"

  # Run Terragrunt apply-all using Google Cloud SDK image as base
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: "bash"
    secretEnv: ["GITHUB_TOKEN"]
    args:
      - "-c"
      - |
        # Install required packages
        apt-get update && apt-get install -y \
          wget \
          unzip \
          git

        # Download and install Terraform
        wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
        unzip terraform_1.6.0_linux_amd64.zip
        mv terraform /usr/local/bin/

        # Verify terraform installation
        terraform version

        # Configure Git to use GITHUB_TOKEN
        git config --global url."https://oauth2:$${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

        # Export the token so terragrunt can access it
        export GITHUB_TOKEN="$${GITHUB_TOKEN}"

        cd environments/stable
        /workspace/terragrunt run-all apply --terragrunt-non-interactive
    id: "terragrunt-apply"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s" # 20 minute timeout

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
